# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9efbe2408dac27bf8c54b91d3bd9deb79cf3e1d43109c28d6ef59e34283af0a4724b6337af4c73bc035a3c16dec6bc98e8a03a8c3e32fca1134ac467edae0b6d

test:
  secret_key_base: bae694fcc5a55bc01704117a4817af4619f05651f474dab3f5690cdb3e79848f67b292ea4b22d9d1532498fd25b50dc1ca3fc2d37d430c5f4651c069d4896f4a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
